---
upload_path: "/images-src/content/:year:/:month:/:day:"
frontmatter_file_url_template: "/content/:year:/:month:/:day:"
body_file_url_template: "/content/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections: 
version: 0.31.1
